[package]
name = "lux"
version = "0.1.0"
description = "A DMX lighting control system for Enttec Open DMX USB devices."
edition = "2021"
rust-version = "1.70"
authors = ["John Carmack"]
repository = "https://github.com/johncarmack1984/lux"
documentation = "https://lux.johncarmack.com"
license = ""
readme = "../README.md"

[lib]
name = "lux_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "^2.0.0-beta", features = ["isolation", "codegen"] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
enttecopendmx = "0.1.0"
log = "^0.4"
thiserror = "1.0.58"
strum = { version = "0.26.2", features = ["derive"] }
strum_macros = "0.26.2"
tauri-plugin-log = "^2.0.0-beta"
tauri-plugin-notification = "^2.0.0-beta"
tiny_http = "0.12.0"
tauri-plugin-http = "^2.0.0-beta"
tauri-plugin-websocket = "2.0.0-beta"
array-init = "2.1.0"

[dependencies.tauri]
version = "^2.0.0-beta"
features = [
    "isolation",
    "image-ico",
    "image-png",
    "macos-private-api",
    "tray-icon",
]

[dev-dependencies.tauri]
version = "^2.0.0-beta"
features = ["devtools", "test", "tracing"]

# ftd2xx dependency
[dependencies.libftd2xx]
version = "0.32.4"
# statically link the vendor library, defaults to dynamic if not set
# this will make things "just work" on Linux and Windows
features = ["static"]

[dependencies.tauri-plugin-sql]
features = ["sqlite"]                                   # or "postgres", or "mysql"
version = "^2.0.0-beta"
git = "https://github.com/tauri-apps/plugins-workspace"
branch = "v2"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem and the built-in dev server is disabled.
# If you use cargo directly instead of tauri's cli you can use this feature flag to switch between tauri's `dev` and `build` modes.
# DO NOT REMOVE!!
prod = ["tauri/custom-protocol"]

# default to small, optimized release binaries
[profile.release]
panic = "unwind"
codegen-units = 1
lto = true
incremental = false
opt-level = "s"

[target."cfg(not(any(target_os = \"android\")))".dependencies]
tauri-plugin-cli = "^2.0.0-beta"
