[package]
name = "lux"
version = "0.1.0"
description = "A DMX lighting control system for Enttec Open DMX USB devices."
authors = ["John Carmack"]
edition = "2021"
repository = "https://github.com/johncarmack1984/lux"
license = "GNU GPLv3"
readme = "../README.md"

[lib]
name = "lux_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.0.0-rc.0", features = ["isolation", "codegen"] }

[dev-dependencies]
tauri = { version = "^2.0.0-beta", features = ["devtools", "test", "tracing"] }

[dependencies]
array-init = "2.1.0"
dotenvy = "0.15.7"
enttecopendmx = "0.1.0"
libftd2xx = { version = "0.32.4", features = ["static"] }
log = "^0.4"
axum = { version = "0.6.20", features = ["tokio"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
strum = { version = "0.26.2", features = ["derive"] }
strum_macros = "0.26.2"
tauri = { version = "2.0.0-rc.0", features = [
    "isolation",
    "image-ico",
    "image-png",
    "tray-icon",
] }
tauri-plugin-log = "2.0.0-rc.0"
tauri-plugin-shell = "2.0.0-rc.0"
thiserror = "1.0.58"
tokio = { version = "1", features = ["full"] }
uuid = { version = "1.4.1", features = [
    "v4", # Lets you generate random UUIDs
    # "fast-rng",          # Use a faster (but still sufficiently random) RNG
    # "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
    "serde", # Enable serialization/deserialization of UUIDs
] }
tauri-plugin-http = "2.0.0-rc.0"
# tauri-plugin-devtools = { git = "https://github.com/crabnebula-dev/devtools" }
# tauri-plugin-cli = "^2.0.0-beta"
# tauri-plugin-notification = "2.0.0-beta"
# tauri-plugin-positioner = { version = "^2.0.0-beta", features = ["tray-icon"] }
# tauri-plugin-window-state = "^2.0.0-beta"
anyhow = "1.0.81"
tower = "0.4.13"

# default to small, optimized release binaries
[profile.release]
panic = "abort"
codegen-units = 1
lto = true
incremental = false
opt-level = "s"
