[package]
name = "lux"
version = "0.1.0"
description = "A DMX lighting control system for Enttec Open DMX USB devices."
edition = "2021"
rust-version = "1.70"
authors = ["John Carmack"]
repository = "https://github.com/johncarmack1984/lux"
license = "GNU GPLv3"
readme = "../README.md"

[lib]
name = "lux_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[dependencies]
array-init = "2.1.0"
enttecopendmx = "0.1.0"
libftd2xx = { version = "0.32.4", features = ["static"] }
log = "^0.4"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
sqlx = { version = "0.7", features = ["runtime-tokio", "sqlite"] }
strum = { version = "0.26.2", features = ["derive"] }
strum_macros = "0.26.2"
tauri = { version = "^2.0.0-beta", features = [
    "isolation",
    "image-ico",
    "image-png",
    "macos-private-api",
    "tray-icon",
] }
tauri-plugin-cli = "^2.0.0-beta"
tauri-plugin-log = "^2.0.0-beta"
tauri-plugin-http = "^2.0.0-beta"
tauri-plugin-positioner = { version = "^2.0.0-beta.3", features = ["tray-icon"] }
tauri-plugin-shell = "2.0.0-beta.3"
tauri-plugin-sql = { version = "^2.0.0-beta", features = ["sqlite"] }
thiserror = "1.0.58"

[build-dependencies]
tauri-build = { version = "^2.0.0-beta", features = ["isolation", "codegen"] }

[dev-dependencies]
tauri = { version = "^2.0.0-beta", features = ["devtools", "test", "tracing"] }

[features]
# this feature is used for production builds or when `devPath` points to the filesystem and the built-in dev server is disabled.
# If you use cargo directly instead of tauri's cli you can use this feature flag to switch between tauri's `dev` and `build` modes.
# DO NOT REMOVE!!
prod = ["tauri/custom-protocol"]

[profile.dev.package.sqlx-macros]
opt-level = 3

# default to small, optimized release binaries
[profile.release]
panic = "unwind"
codegen-units = 1
lto = true
incremental = false
opt-level = "s"
