// This file has been generated by tauri_typed_ipc. DO NOT EDIT.

import { invoke } from "@tauri-apps/api/core";
import { listen } from "@tauri-apps/api/event";

export const cmd = {
  /** @throws {string} */
  set_buffer(buffer: number[]): Promise<LuxBuffer> {
    return invoke("cmd.set_buffer", { buffer });
  },

  /** @throws {string} */
  update_channel_value(channelNumber: number, value: number): Promise<LuxBuffer> {
    return invoke("cmd.update_channel_value", { channel_number: channelNumber, value });
  },

  /** @throws {string} */
  insert_channel(newMetadata: LuxChannel): Promise<LuxChannel> {
    return invoke("cmd.insert_channel", { new_metadata: newMetadata });
  },

  /** @throws {string} */
  update_channel_metadata(channelNumber: number, newMetadata: LuxChannel): Promise<LuxChannel> {
    return invoke("cmd.update_channel_metadata", { channel_number: channelNumber, new_metadata: newMetadata });
  },

  /** @throws {string} */
  sync_state(): Promise<string> {
    return invoke("cmd.sync_state");
  },

  /** @throws {string} */
  list_presets(): Promise<FixturePreset[]> {
    return invoke("cmd.list_presets");
  },

  /** @throws {string} */
  get_patch(): Promise<Fixture[]> {
    return invoke("cmd.get_patch");
  },

  /** @throws {string} */
  add_fixture(name: string, address: number, channels: ChannelDef[]): Promise<Fixture[]> {
    return invoke("cmd.add_fixture", { name, address, channels });
  },

  /** @throws {string} */
  update_fixture(id: string, name: string, address: number, channels: ChannelDef[]): Promise<Fixture[]> {
    return invoke("cmd.update_fixture", { id, name, address, channels });
  },

  /** @throws {string} */
  remove_fixture(id: string): Promise<Fixture[]> {
    return invoke("cmd.remove_fixture", { id });
  },

  /** @throws {string} */
  list_setups(): Promise<SetupSummary[]> {
    return invoke("cmd.list_setups");
  },

  /** @throws {string} */
  create_setup(name: string, universe: number): Promise<SetupSummary[]> {
    return invoke("cmd.create_setup", { name, universe });
  },

  /** @throws {string} */
  rename_setup(id: string, name: string): Promise<SetupSummary[]> {
    return invoke("cmd.rename_setup", { id, name });
  },

  /** @throws {string} */
  set_setup_universe(id: string, universe: number): Promise<SetupSummary[]> {
    return invoke("cmd.set_setup_universe", { id, universe });
  },

  /** @throws {string} */
  delete_setup(id: string): Promise<SetupSummary[]> {
    return invoke("cmd.delete_setup", { id });
  },

  /** @throws {string} */
  set_active_setup(id: string): Promise<SetupSummary> {
    return invoke("cmd.set_active_setup", { id });
  },

  /** @throws {string} */
  get_collapsed_fixtures(): Promise<string[]> {
    return invoke("cmd.get_collapsed_fixtures");
  },

  /** @throws {string} */
  set_fixture_collapsed(id: string, collapsed: boolean): Promise<string[]> {
    return invoke("cmd.set_fixture_collapsed", { id, collapsed });
  },

  /** @throws {string} */
  get_settings(): Promise<UserSettings> {
    return invoke("cmd.get_settings");
  },

  /** @throws {string} */
  set_slider_orientation(orientation: SliderOrientation): Promise<UserSettings> {
    return invoke("cmd.set_slider_orientation", { orientation });
  },

  /** @throws {string} */
  auth_status(): Promise<AuthStatus> {
    return invoke("cmd.auth_status");
  },

  /** @throws {string} */
  sign_up(email: string, password: string): Promise<null> {
    return invoke("cmd.sign_up", { email, password });
  },

  /** @throws {string} */
  confirm_sign_up(email: string, code: string): Promise<null> {
    return invoke("cmd.confirm_sign_up", { email, code });
  },

  /** @throws {string} */
  sign_in(email: string, password: string): Promise<AuthStatus> {
    return invoke("cmd.sign_in", { email, password });
  },

  /** @throws {string} */
  sign_in_with_apple(): Promise<AuthStatus> {
    return invoke("cmd.sign_in_with_apple");
  },

  /** @throws {string} */
  sign_out(): Promise<AuthStatus> {
    return invoke("cmd.sign_out");
  },

  /** @throws {string} */
  delete_account(): Promise<AuthStatus> {
    return invoke("cmd.delete_account");
  },

  /** @throws {string} */
  sync_status(): Promise<SyncState> {
    return invoke("cmd.sync_status");
  },

  /** @throws {string} */
  sync_now(): Promise<null> {
    return invoke("cmd.sync_now");
  },

  /** @throws {string} */
  list_remote_peers(): Promise<RemotePeer[]> {
    return invoke("cmd.list_remote_peers");
  },

  /** @throws {string} */
  list_paired_devices(): Promise<PairedDevice[]> {
    return invoke("cmd.list_paired_devices");
  },

  /** @throws {string} */
  list_pending_devices(): Promise<PendingDevice[]> {
    return invoke("cmd.list_pending_devices");
  },

  /** @throws {string} */
  approve_device(pairRef: string, setupId: string, universe: number | null, name: string | null): Promise<null> {
    return invoke("cmd.approve_device", { pair_ref: pairRef, setup_id: setupId, universe, name });
  },

  /** @throws {string} */
  remove_device(deviceId: string): Promise<null> {
    return invoke("cmd.remove_device", { device_id: deviceId });
  },

  /** @throws {string} */
  list_shares(): Promise<ShareTally> {
    return invoke("cmd.list_shares");
  },

  /** @throws {string} */
  claim_share(code: string): Promise<SharedSetup> {
    return invoke("cmd.claim_share", { code });
  },

  /** @throws {string} */
  list_shared_setups(): Promise<SharedSetup[]> {
    return invoke("cmd.list_shared_setups");
  },

  /** @throws {string} */
  open_shared_desk(ownerSub: string, setupId: string): Promise<{
	ownerSub: string,
	setupId: string,
	/**  The setup's live name, from the compiled config. */
	name: string,
	universe: number,
	channels: SharedChannel[],
	fixtures: SharedFixture[],
	/**
	 *  The owner applier's last-applied buffer. Empty when it hasn't published
	 *  one — a surface should render zeros, not refuse to draw.
	 */
	buffer: number[],
} | null> {
    return invoke("cmd.open_shared_desk", { owner_sub: ownerSub, setup_id: setupId });
  },

  /** @throws {string} */
  close_shared_desk(): Promise<null> {
    return invoke("cmd.close_shared_desk");
  },

  /** @throws {string} */
  set_shared_channel(channelNumber: number, value: number): Promise<null> {
    return invoke("cmd.set_shared_channel", { channel_number: channelNumber, value });
  },

  /** @throws {string} */
  set_shared_buffer(buffer: number[]): Promise<null> {
    return invoke("cmd.set_shared_buffer", { buffer });
  },

  /** @throws {string} */
  list_dmx_devices(): Promise<DmxDeviceInfo[]> {
    return invoke("cmd.list_dmx_devices");
  },

  /** @throws {string} */
  set_dmx_device(key: string): Promise<DmxDeviceInfo[]> {
    return invoke("cmd.set_dmx_device", { key });
  },

  /** @throws {string} */
  rescan_dmx_devices(): Promise<null> {
    return invoke("cmd.rescan_dmx_devices");
  },
};

export const sync = {
  /** @throws {string} */
  sync_buffer(): Promise<LuxBuffer> {
    return invoke("sync.sync_buffer");
  },

  /** @throws {string} */
  sync_channels(): Promise<LuxChannels> {
    return invoke("sync.sync_channels");
  },

  /** @throws {string} */
  sync_state(): Promise<string> {
    return invoke("sync.sync_state");
  },
};

export type CmdEvent = { type: "channelDataSet"; channels: LuxChannel[] } | { type: "patchSet"; setup_id: string; fixtures: Fixture[] } | { type: "setupsChanged"; setups: SetupSummary[]; active_setup_id: string } | { type: "settingsChanged"; settings: UserSettings } | { type: "authChanged"; status: AuthStatus } | { type: "syncStatusChanged"; state: SyncState } | { type: "dmxDevicesChanged"; devices: DmxDeviceInfo[] };

export type SyncEvent = { type: "bufferSet"; buffer: number[] };

export const events = {
  cmd: {
    async listen(callback: (event: CmdEvent) => void): Promise<() => void> {
      const unlisten = await Promise.all([
        listen<{ channels: LuxChannel[] }>("cmd:channelDataSet", (event) => callback({ type: "channelDataSet", ...event.payload })),
        listen<{ setup_id: string; fixtures: Fixture[] }>("cmd:patchSet", (event) => callback({ type: "patchSet", ...event.payload })),
        listen<{ setups: SetupSummary[]; active_setup_id: string }>("cmd:setupsChanged", (event) => callback({ type: "setupsChanged", ...event.payload })),
        listen<{ settings: UserSettings }>("cmd:settingsChanged", (event) => callback({ type: "settingsChanged", ...event.payload })),
        listen<{ status: AuthStatus }>("cmd:authChanged", (event) => callback({ type: "authChanged", ...event.payload })),
        listen<{ state: SyncState }>("cmd:syncStatusChanged", (event) => callback({ type: "syncStatusChanged", ...event.payload })),
        listen<{ devices: DmxDeviceInfo[] }>("cmd:dmxDevicesChanged", (event) => callback({ type: "dmxDevicesChanged", ...event.payload })),
      ]);
      return () => unlisten.forEach((un) => un());
    },
  },

  sync: {
    listen(callback: (event: SyncEvent) => void): Promise<() => void> {
      return listen<{ buffer: number[] }>("sync:bufferSet", (event) => callback({ type: "bufferSet", ...event.payload }));
    },
  },
};

export const createTauRPCProxy = () => ({
  cmd: { ...cmd, event: { on: events.cmd.listen } },
  sync: { ...sync, event: { on: events.sync.listen } },
});

/**
 *  Auth status crossing IPC: whether accounts are configured at all, whether
 *  someone is signed in, and their email.
 */
export type AuthStatus = {
	configured: boolean,
	signedIn: boolean,
	email: string | null,
	/**  How the signed-in session was established; `None` when signed out. */
	provider: Provider | null,
	/**
	 *  Whether native Sign in with Apple is available in this build (platform
	 *  carries the entitlement AND the backend URL is configured).
	 */
	apple: boolean,
};

export type Channel = {
	id: string,
	disabled: boolean,
	channelNumber: number,
	label: string,
	labelColor: LuxLabelColor,
};

/**  One channel within a fixture. */
export type ChannelDef = {
	/**  Semantic role — drives the colour swatch / control affordance. */
	role: LuxLabelColor,
	label: string,
};

/**
 *  A detected output as the front-end picker sees it: stable `key`, display
 *  `label`, and whether it's the active output. The desktop tray reads
 *  [`Device`] directly; this is the serializable view for the in-app picker,
 *  which is the only output selector on mobile (there's no tray).
 */
export type DmxDeviceInfo = {
	key: string,
	label: string,
	active: boolean,
};

/**  A patched fixture: `channels.len()` consecutive slots from `address` (1-based). */
export type Fixture = {
	id: string,
	name: string,
	address: number,
	channels: ChannelDef[],
};

/**  A built-in starting point for the "new fixture" flow. */
export type FixturePreset = {
	key: string,
	name: string,
	channels: ChannelDef[],
};

export type LuxBuffer = {
	buffer: number[],
};

export type LuxChannel = Channel;

export type LuxChannels = {
	channels: LuxChannel[],
};

export type LuxLabelColor = "Red" | "Green" | "Blue" | "Amber" | "White" | "Brightness" | 
/**  Raw universe channels (7..=512) with no fixed colour role. */
"Generic";

/**
 *  One paired headless device (a lux-node box) on the account, mirrored from
 *  [`lux_wire::device::DeviceRecord`] for the Devices list and the
 *  delete-account confirm's tally. `paired_at` is epoch millis (an `f64` so it
 *  crosses to the webview as a plain `number`).
 */
export type PairedDevice = {
	deviceId: string,
	name: string,
	hostname: string,
	setupId: string,
	universe: number,
	pairedAt: number | null,
};

/**
 *  One pending (unclaimed, same-egress) device on the Add-device screen,
 *  mirrored from [`lux_wire::device::PendingDevice`]. `pair_ref` is the opaque
 *  handle the approve call takes; `first_seen` is epoch millis as an `f64`.
 */
export type PendingDevice = {
	pairRef: string,
	userCode: string,
	hostname: string,
	macTail: string,
	version: string,
	arch: string,
	firstSeen: number | null,
};

/**
 *  How the current session was established. Password sessions can change
 *  their password and re-auth by SRP; Apple sessions re-auth by sheet. Stored
 *  with the session so a restart keeps the distinction.
 */
export type Provider = "password" | "apple";

/**
 *  One of the user's other signed-in devices, as the UI sees it (a thinned
 *  [`lux_wire::ctl::PresenceCard`]). A peer whose `setup_id` matches the
 *  active setup is an applier for it: touches here apply there.
 */
export type RemotePeer = {
	session: string,
	setupId: string,
	name: string,
};

/**
 *  A lightweight setup descriptor for the switcher UI — no fixtures, so listing
 *  setups doesn't ship every patch.
 */
export type SetupSummary = {
	id: string,
	name: string,
	universe: number,
	fixtureCount: number,
	active: boolean,
};

/**
 *  Who the account's shared-control grants involve, thinned from
 *  [`lux_wire::shares::SharesResponse`] to the names a confirm dialog reads
 *  out. One person holding two of the caller's setups is one name here — the
 *  dialog counts *people*, because that is what the user is about to affect.
 */
export type ShareTally = {
	/**  People who can currently control one of the caller's setups. */
	grantedTo: string[],
	/**  People whose setups the caller can currently control. */
	receivedFrom: string[],
};

/**  One patched slot on a shared desk (`lux_wire::ctl::ConfigChannel`). */
export type SharedChannel = {
	/**  1-based DMX slot. */
	n: number,
	name: string,
	/**
	 *  Role name; a surface matches the ones it knows and treats the rest as a
	 *  plain fader, so an unfamiliar value is never an error.
	 */
	role: string,
};

/**
 *  Everything a guest surface needs to draw one shared setup: the owner's
 *  compiled setup, flattened, plus their applier's last-known buffer so the
 *  faders open at the truth instead of at zero.
 * 
 *  Returned whole rather than as separate calls because a guest has no copy of
 *  any of it — there is no local store to read a second time, and a surface
 *  that drew before the buffer arrived would show a dark desk that isn't.
 */
export type SharedDesk = {
	ownerSub: string,
	setupId: string,
	/**  The setup's live name, from the compiled config. */
	name: string,
	universe: number,
	channels: SharedChannel[],
	fixtures: SharedFixture[],
	/**
	 *  The owner applier's last-applied buffer. Empty when it hasn't published
	 *  one — a surface should render zeros, not refuse to draw.
	 */
	buffer: number[],
};

/**  One fixture on a shared desk (`lux_wire::ctl::ConfigFixture`). */
export type SharedFixture = {
	name: string,
	address: number,
	count: number,
};

/**  One setup another account has shared with this one, as a surface sees it. */
export type SharedSetup = {
	/**  The owner's Cognito sub — the ctl topic space this grant addresses. */
	ownerSub: string,
	/**  How the owner appears in the list (their account email). */
	ownerLabel: string,
	setupId: string,
	/**
	 *  The name recorded when the grant was created. The live name rides the
	 *  compiled config; this is what the list shows before one arrives.
	 */
	setupName: string | null,
	/**
	 *  True once the owner's compiled config has arrived, which is what a
	 *  surface needs before it can draw anything. False means the owner's
	 *  applier has not published one — it may simply not be running.
	 */
	renderable: boolean,
};

/**
 *  Which way the universe desk's faders run: vertical sliders in a
 *  horizontally-scrolling desk (the classic lighting-console layout, and the
 *  default), or horizontal sliders in a vertically-scrolling list.
 */
export type SliderOrientation = "vertical" | "horizontal";

/**  Coarse cloud-sync state for the nav indicator. */
export type SyncState = 
/**  Signed out, or signed in with nothing left to sync. */
"idle" | 
/**  A push or pull is in flight. */
"syncing" | 
/**  The last cycle completed and everything is flushed. */
"synced" | 
/**  The last attempt couldn't reach the cloud; a backoff retry is running. */
"offline";

/**
 *  The user's synced preferences. Add fields with
 *  `#[serde(default, deserialize_with = "ok_or_default")]` only — see the
 *  module docs for why.
 */
export type UserSettings = {
	sliderOrientation?: SliderOrientation,
};
