// This file has been generated by tauri_typed_ipc. DO NOT EDIT.

import { invoke } from "@tauri-apps/api/core";
import { listen } from "@tauri-apps/api/event";

export const cmd = {
  /** @throws {string} */
  set_buffer(buffer: number[]): Promise<LuxBuffer> {
    return invoke("cmd.set_buffer", { buffer });
  },

  /** @throws {string} */
  update_channel_value(channelNumber: number, value: number): Promise<LuxBuffer> {
    return invoke("cmd.update_channel_value", { channel_number: channelNumber, value });
  },

  /** @throws {string} */
  insert_channel(newMetadata: LuxChannel): Promise<LuxChannel> {
    return invoke("cmd.insert_channel", { new_metadata: newMetadata });
  },

  /** @throws {string} */
  update_channel_metadata(channelNumber: number, newMetadata: LuxChannel): Promise<LuxChannel> {
    return invoke("cmd.update_channel_metadata", { channel_number: channelNumber, new_metadata: newMetadata });
  },

  /** @throws {string} */
  sync_state(): Promise<string> {
    return invoke("cmd.sync_state");
  },

  /** @throws {string} */
  list_presets(): Promise<FixturePreset[]> {
    return invoke("cmd.list_presets");
  },

  /** @throws {string} */
  get_patch(): Promise<Fixture[]> {
    return invoke("cmd.get_patch");
  },

  /** @throws {string} */
  add_fixture(name: string, address: number, channels: ChannelDef[]): Promise<Fixture[]> {
    return invoke("cmd.add_fixture", { name, address, channels });
  },

  /** @throws {string} */
  update_fixture(id: string, name: string, address: number, channels: ChannelDef[]): Promise<Fixture[]> {
    return invoke("cmd.update_fixture", { id, name, address, channels });
  },

  /** @throws {string} */
  remove_fixture(id: string): Promise<Fixture[]> {
    return invoke("cmd.remove_fixture", { id });
  },

  /** @throws {string} */
  list_setups(): Promise<SetupSummary[]> {
    return invoke("cmd.list_setups");
  },

  /** @throws {string} */
  create_setup(name: string, universe: number): Promise<SetupSummary[]> {
    return invoke("cmd.create_setup", { name, universe });
  },

  /** @throws {string} */
  rename_setup(id: string, name: string): Promise<SetupSummary[]> {
    return invoke("cmd.rename_setup", { id, name });
  },

  /** @throws {string} */
  set_setup_universe(id: string, universe: number): Promise<SetupSummary[]> {
    return invoke("cmd.set_setup_universe", { id, universe });
  },

  /** @throws {string} */
  delete_setup(id: string): Promise<SetupSummary[]> {
    return invoke("cmd.delete_setup", { id });
  },

  /** @throws {string} */
  set_active_setup(id: string): Promise<SetupSummary> {
    return invoke("cmd.set_active_setup", { id });
  },

  /** @throws {string} */
  auth_status(): Promise<AuthStatus> {
    return invoke("cmd.auth_status");
  },

  /** @throws {string} */
  sign_up(email: string, password: string): Promise<null> {
    return invoke("cmd.sign_up", { email, password });
  },

  /** @throws {string} */
  confirm_sign_up(email: string, code: string): Promise<null> {
    return invoke("cmd.confirm_sign_up", { email, code });
  },

  /** @throws {string} */
  sign_in(email: string, password: string): Promise<AuthStatus> {
    return invoke("cmd.sign_in", { email, password });
  },

  /** @throws {string} */
  sign_out(): Promise<AuthStatus> {
    return invoke("cmd.sign_out");
  },

  /** @throws {string} */
  delete_account(): Promise<AuthStatus> {
    return invoke("cmd.delete_account");
  },

  /** @throws {string} */
  sync_status(): Promise<SyncState> {
    return invoke("cmd.sync_status");
  },

  /** @throws {string} */
  sync_now(): Promise<null> {
    return invoke("cmd.sync_now");
  },

  /** @throws {string} */
  list_dmx_devices(): Promise<DmxDeviceInfo[]> {
    return invoke("cmd.list_dmx_devices");
  },

  /** @throws {string} */
  set_dmx_device(key: string): Promise<DmxDeviceInfo[]> {
    return invoke("cmd.set_dmx_device", { key });
  },

  /** @throws {string} */
  rescan_dmx_devices(): Promise<null> {
    return invoke("cmd.rescan_dmx_devices");
  },
};

export const sync = {
  /** @throws {string} */
  sync_buffer(): Promise<LuxBuffer> {
    return invoke("sync.sync_buffer");
  },

  /** @throws {string} */
  sync_channels(): Promise<LuxChannels> {
    return invoke("sync.sync_channels");
  },

  /** @throws {string} */
  sync_state(): Promise<string> {
    return invoke("sync.sync_state");
  },
};

export type CmdEvent = { type: "channelDataSet"; channels: LuxChannel[] } | { type: "patchSet"; setup_id: string; fixtures: Fixture[] } | { type: "setupsChanged"; setups: SetupSummary[]; active_setup_id: string } | { type: "authChanged"; status: AuthStatus } | { type: "syncStatusChanged"; state: SyncState } | { type: "dmxDevicesChanged"; devices: DmxDeviceInfo[] };

export type SyncEvent = { type: "bufferSet"; buffer: number[] };

export const events = {
  cmd: {
    async listen(callback: (event: CmdEvent) => void): Promise<() => void> {
      const unlisten = await Promise.all([
        listen<{ channels: LuxChannel[] }>("cmd:channelDataSet", (event) => callback({ type: "channelDataSet", ...event.payload })),
        listen<{ setup_id: string; fixtures: Fixture[] }>("cmd:patchSet", (event) => callback({ type: "patchSet", ...event.payload })),
        listen<{ setups: SetupSummary[]; active_setup_id: string }>("cmd:setupsChanged", (event) => callback({ type: "setupsChanged", ...event.payload })),
        listen<{ status: AuthStatus }>("cmd:authChanged", (event) => callback({ type: "authChanged", ...event.payload })),
        listen<{ state: SyncState }>("cmd:syncStatusChanged", (event) => callback({ type: "syncStatusChanged", ...event.payload })),
        listen<{ devices: DmxDeviceInfo[] }>("cmd:dmxDevicesChanged", (event) => callback({ type: "dmxDevicesChanged", ...event.payload })),
      ]);
      return () => unlisten.forEach((un) => un());
    },
  },

  sync: {
    listen(callback: (event: SyncEvent) => void): Promise<() => void> {
      return listen<{ buffer: number[] }>("sync:bufferSet", (event) => callback({ type: "bufferSet", ...event.payload }));
    },
  },
};

export const createTauRPCProxy = () => ({
  cmd: { ...cmd, event: { on: events.cmd.listen } },
  sync: { ...sync, event: { on: events.sync.listen } },
});

/**
 *  Auth status crossing IPC: whether accounts are configured at all, whether
 *  someone is signed in, and their email.
 */
export type AuthStatus = {
	configured: boolean,
	signedIn: boolean,
	email: string | null,
};

export type Channel = {
	id: string,
	disabled: boolean,
	channelNumber: number,
	label: string,
	labelColor: LuxLabelColor,
};

/**  One channel within a fixture. */
export type ChannelDef = {
	/**  Semantic role — drives the colour swatch / control affordance. */
	role: LuxLabelColor,
	label: string,
};

/**
 *  A detected output as the front-end picker sees it: stable `key`, display
 *  `label`, and whether it's the active output. The desktop tray reads
 *  [`Device`] directly; this is the serializable view for the in-app picker,
 *  which is the only output selector on mobile (there's no tray).
 */
export type DmxDeviceInfo = {
	key: string,
	label: string,
	active: boolean,
};

/**  A patched fixture: `channels.len()` consecutive slots from `address` (1-based). */
export type Fixture = {
	id: string,
	name: string,
	address: number,
	channels: ChannelDef[],
};

/**  A built-in starting point for the "new fixture" flow. */
export type FixturePreset = {
	key: string,
	name: string,
	channels: ChannelDef[],
};

export type LuxBuffer = {
	buffer: number[],
};

export type LuxChannel = Channel;

export type LuxChannels = {
	channels: LuxChannel[],
};

export type LuxLabelColor = "Red" | "Green" | "Blue" | "Amber" | "White" | "Brightness" | 
/**  Raw universe channels (7..=512) with no fixed colour role. */
"Generic";

/**
 *  A lightweight setup descriptor for the switcher UI — no fixtures, so listing
 *  setups doesn't ship every patch.
 */
export type SetupSummary = {
	id: string,
	name: string,
	universe: number,
	fixtureCount: number,
	active: boolean,
};

/**  Coarse cloud-sync state for the nav indicator. */
export type SyncState = 
/**  Signed out, or signed in with nothing left to sync. */
"idle" | 
/**  A push or pull is in flight. */
"syncing" | 
/**  The last cycle completed and everything is flushed. */
"synced" | 
/**  The last attempt couldn't reach the cloud; a backoff retry is running. */
"offline";
