// This file has been generated by Specta. DO NOT EDIT.

export type TauRpcApiInputTypes = { proc_name: "sync_state"; input_type: null }

export type TauRpcEventsInputTypes = { proc_name: "event"; input_type: null }

export type TauRpcEventsOutputTypes = { proc_name: "event"; output_type: null }

export type TauRpcApiOutputTypes = { proc_name: "sync_state"; output_type: null }

const ARGS_MAP = {"events":"{\"event\":[]}","":"{\"sync_state\":[]}"}
import { createTauRPCProxy as createProxy } from "taurpc"

export const createTauRPCProxy = () => createProxy<Router>(ARGS_MAP)

type Router = {
	'': [TauRpcApiInputTypes, TauRpcApiOutputTypes],
	'events': [TauRpcEventsInputTypes, TauRpcEventsOutputTypes],
}