// This file has been generated by tauri_typed_ipc. DO NOT EDIT.

import { invoke } from "@tauri-apps/api/core";
import { listen } from "@tauri-apps/api/event";

export const cmd = {
  /** @throws {string} */
  set_buffer(buffer: number[]): Promise<LuxBuffer> {
    return invoke("cmd.set_buffer", { buffer });
  },

  /** @throws {string} */
  update_channel_value(channelNumber: number, value: number): Promise<LuxBuffer> {
    return invoke("cmd.update_channel_value", { channel_number: channelNumber, value });
  },

  /** @throws {string} */
  insert_channel(newMetadata: LuxChannel): Promise<LuxChannel> {
    return invoke("cmd.insert_channel", { new_metadata: newMetadata });
  },

  /** @throws {string} */
  update_channel_metadata(channelNumber: number, newMetadata: LuxChannel): Promise<LuxChannel> {
    return invoke("cmd.update_channel_metadata", { channel_number: channelNumber, new_metadata: newMetadata });
  },

  /** @throws {string} */
  sync_state(): Promise<string> {
    return invoke("cmd.sync_state");
  },

  /** @throws {string} */
  list_presets(): Promise<FixturePreset[]> {
    return invoke("cmd.list_presets");
  },

  /** @throws {string} */
  get_patch(): Promise<Fixture[]> {
    return invoke("cmd.get_patch");
  },

  /** @throws {string} */
  add_fixture(name: string, address: number, channels: ChannelDef[]): Promise<Fixture[]> {
    return invoke("cmd.add_fixture", { name, address, channels });
  },

  /** @throws {string} */
  update_fixture(id: string, name: string, address: number, channels: ChannelDef[]): Promise<Fixture[]> {
    return invoke("cmd.update_fixture", { id, name, address, channels });
  },

  /** @throws {string} */
  remove_fixture(id: string): Promise<Fixture[]> {
    return invoke("cmd.remove_fixture", { id });
  },

  /** @throws {string} */
  list_setups(): Promise<SetupSummary[]> {
    return invoke("cmd.list_setups");
  },

  /** @throws {string} */
  create_setup(name: string, universe: number): Promise<SetupSummary[]> {
    return invoke("cmd.create_setup", { name, universe });
  },

  /** @throws {string} */
  rename_setup(id: string, name: string): Promise<SetupSummary[]> {
    return invoke("cmd.rename_setup", { id, name });
  },

  /** @throws {string} */
  set_setup_universe(id: string, universe: number): Promise<SetupSummary[]> {
    return invoke("cmd.set_setup_universe", { id, universe });
  },

  /** @throws {string} */
  delete_setup(id: string): Promise<SetupSummary[]> {
    return invoke("cmd.delete_setup", { id });
  },

  /** @throws {string} */
  set_active_setup(id: string): Promise<SetupSummary> {
    return invoke("cmd.set_active_setup", { id });
  },
};

export const sync = {
  /** @throws {string} */
  sync_buffer(): Promise<LuxBuffer> {
    return invoke("sync.sync_buffer");
  },

  /** @throws {string} */
  sync_channels(): Promise<LuxChannels> {
    return invoke("sync.sync_channels");
  },

  /** @throws {string} */
  sync_state(): Promise<string> {
    return invoke("sync.sync_state");
  },
};

export type CmdEvent = { type: "channelDataSet"; channels: LuxChannel[] } | { type: "patchSet"; setup_id: string; fixtures: Fixture[] } | { type: "setupsChanged"; setups: SetupSummary[]; active_setup_id: string };

export type SyncEvent = { type: "bufferSet"; buffer: number[] };

export const events = {
  cmd: {
    async listen(callback: (event: CmdEvent) => void): Promise<() => void> {
      const unlisten = await Promise.all([
        listen<{ channels: LuxChannel[] }>("cmd:channelDataSet", (event) => callback({ type: "channelDataSet", ...event.payload })),
        listen<{ setup_id: string; fixtures: Fixture[] }>("cmd:patchSet", (event) => callback({ type: "patchSet", ...event.payload })),
        listen<{ setups: SetupSummary[]; active_setup_id: string }>("cmd:setupsChanged", (event) => callback({ type: "setupsChanged", ...event.payload })),
      ]);
      return () => unlisten.forEach((un) => un());
    },
  },

  sync: {
    listen(callback: (event: SyncEvent) => void): Promise<() => void> {
      return listen<{ buffer: number[] }>("sync:bufferSet", (event) => callback({ type: "bufferSet", ...event.payload }));
    },
  },
};

export const createTauRPCProxy = () => ({
  cmd: { ...cmd, event: { on: events.cmd.listen } },
  sync: { ...sync, event: { on: events.sync.listen } },
});

export type Channel = {
	id: string,
	disabled: boolean,
	channelNumber: number,
	label: string,
	labelColor: LuxLabelColor,
};

/**  One channel within a fixture. */
export type ChannelDef = {
	/**  Semantic role — drives the colour swatch / control affordance. */
	role: LuxLabelColor,
	label: string,
};

/**  A patched fixture: `channels.len()` consecutive slots from `address` (1-based). */
export type Fixture = {
	id: string,
	name: string,
	address: number,
	channels: ChannelDef[],
};

/**  A built-in starting point for the "new fixture" flow. */
export type FixturePreset = {
	key: string,
	name: string,
	channels: ChannelDef[],
};

export type LuxBuffer = {
	buffer: number[],
};

export type LuxChannel = Channel;

export type LuxChannels = {
	channels: LuxChannel[],
};

export type LuxLabelColor = "Red" | "Green" | "Blue" | "Amber" | "White" | "Brightness" | 
/**  Raw universe channels (7..=512) with no fixed colour role. */
"Generic";

/**
 *  A lightweight setup descriptor for the switcher UI — no fixtures, so listing
 *  setups doesn't ship every patch.
 */
export type SetupSummary = {
	id: string,
	name: string,
	universe: number,
	fixtureCount: number,
	active: boolean,
};
