// This file has been generated by Specta. DO NOT EDIT.

import {
  createTauRPCProxy as createProxy,
  type InferCommandOutput,
} from "taurpc";
type TAURI_CHANNEL<T> = (response: T) => void;

export type Channel = {
  id: string;
  disabled: boolean;
  channelNumber: number;
  label: string;
  labelColor: LuxLabelColor;
};

export type LuxBuffer = {
  buffer: [number, number, number, number, number, number];
};

export type LuxChannel = Channel;

export type LuxChannels = {
  channels: [
    LuxChannel,
    LuxChannel,
    LuxChannel,
    LuxChannel,
    LuxChannel,
    LuxChannel,
  ];
};

export type LuxLabelColor =
  | "Red"
  | "Green"
  | "Blue"
  | "Amber"
  | "White"
  | "Brightness";

const ARGS_MAP = {
  cmd: '{"channel_data_set":["channels"],"delete_channel":["channel_number"],"insert_channel":["new_metadata"],"set_buffer":["buffer"],"sync_state":[],"update_channel_metadata":["channel_number","new_metadata"],"update_channel_value":["channel_number","value"]}',
  sync: '{"buffer_set":["buffer"],"sync_buffer":[],"sync_channels":[],"sync_state":[]}',
};
export type Router = {
  cmd: {
    channel_data_set: (
      channels: [
        LuxChannel,
        LuxChannel,
        LuxChannel,
        LuxChannel,
        LuxChannel,
        LuxChannel,
      ],
    ) => Promise<void>;
    delete_channel: (channelNumber: number) => Promise<null>;
    insert_channel: (newMetadata: LuxChannel) => Promise<LuxChannel>;
    set_buffer: (
      buffer: [number, number, number, number, number, number],
    ) => Promise<LuxBuffer>;
    sync_state: () => Promise<string>;
    update_channel_metadata: (
      channelNumber: number,
      newMetadata: LuxChannel,
    ) => Promise<LuxChannel>;
    update_channel_value: (
      channelNumber: number,
      value: number,
    ) => Promise<LuxBuffer>;
  };
  sync: {
    buffer_set: (
      buffer: [number, number, number, number, number, number],
    ) => Promise<void>;
    sync_buffer: () => Promise<LuxBuffer>;
    sync_channels: () => Promise<LuxChannels>;
    sync_state: () => Promise<string>;
  };
};

export const createTauRPCProxy = () => createProxy<Router>(ARGS_MAP);
export type { InferCommandOutput };
