// This file has been generated by tauri_typed_ipc. DO NOT EDIT.

import { invoke } from "@tauri-apps/api/core";
import { listen } from "@tauri-apps/api/event";

export const cmd = {
  /** @throws {string} */
  set_buffer(buffer: [number, number, number, number, number, number]): Promise<LuxBuffer> {
    return invoke("cmd.set_buffer", { buffer });
  },

  /** @throws {string} */
  update_channel_value(channelNumber: number, value: number): Promise<LuxBuffer> {
    return invoke("cmd.update_channel_value", { channel_number: channelNumber, value });
  },

  /** @throws {string} */
  insert_channel(newMetadata: LuxChannel): Promise<LuxChannel> {
    return invoke("cmd.insert_channel", { new_metadata: newMetadata });
  },

  /** @throws {string} */
  delete_channel(channelNumber: number): Promise<null> {
    return invoke("cmd.delete_channel", { channel_number: channelNumber });
  },

  /** @throws {string} */
  update_channel_metadata(channelNumber: number, newMetadata: LuxChannel): Promise<LuxChannel> {
    return invoke("cmd.update_channel_metadata", { channel_number: channelNumber, new_metadata: newMetadata });
  },

  /** @throws {string} */
  sync_state(): Promise<string> {
    return invoke("cmd.sync_state");
  },
};

export const sync = {
  /** @throws {string} */
  sync_buffer(): Promise<LuxBuffer> {
    return invoke("sync.sync_buffer");
  },

  /** @throws {string} */
  sync_channels(): Promise<LuxChannels> {
    return invoke("sync.sync_channels");
  },

  /** @throws {string} */
  sync_state(): Promise<string> {
    return invoke("sync.sync_state");
  },
};

export type CmdEvent = { type: "channelDataSet"; channels: [LuxChannel, LuxChannel, LuxChannel, LuxChannel, LuxChannel, LuxChannel] };

export type SyncEvent = { type: "bufferSet"; buffer: [number, number, number, number, number, number] };

export const events = {
  cmd: {
    listen(callback: (event: CmdEvent) => void): Promise<() => void> {
      return listen<{ channels: [LuxChannel, LuxChannel, LuxChannel, LuxChannel, LuxChannel, LuxChannel] }>("cmd:channelDataSet", (event) => callback({ type: "channelDataSet", ...event.payload }));
    },
  },

  sync: {
    listen(callback: (event: SyncEvent) => void): Promise<() => void> {
      return listen<{ buffer: [number, number, number, number, number, number] }>("sync:bufferSet", (event) => callback({ type: "bufferSet", ...event.payload }));
    },
  },
};

export const createTauRPCProxy = () => ({
  cmd: { ...cmd, event: { on: events.cmd.listen } },
  sync: { ...sync, event: { on: events.sync.listen } },
});

export type Channel = {
	id: string,
	disabled: boolean,
	channelNumber: number,
	label: string,
	labelColor: LuxLabelColor,
};

export type LuxBuffer = {
	buffer: [number, number, number, number, number, number],
};

export type LuxChannel = Channel;

export type LuxChannels = {
	channels: [LuxChannel, LuxChannel, LuxChannel, LuxChannel, LuxChannel, LuxChannel],
};

export type LuxLabelColor = "Red" | "Green" | "Blue" | "Amber" | "White" | "Brightness";
